version: 2
jobs:
  build:
    docker:
      - image: francois2/hugo-node
    steps:
      - checkout
      - run: npm ci
      - run: hugo

  deploy:
    machine:
      enabled: true
    steps:
      - run: bin/build-and-deploy-preprod.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
