version: 2.1
jobs:
  build:
    docker:
      - image: francois2/hugo-node
    steps:
      - checkout
      - run: npm ci
      - run: hugo

  deploy:
    steps:
      - run:
        - name: Déploiement
        - command: |
          rsync -avz -e "ssh" --progress public $SSH_USER@$SSH_HOST:$CIRCLE_BRANCH

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
